"Python 2.7":
  script:
  - "PY_EXE=python2.7 bash ./run-tests-for-ci.sh"
  tags:
  - python2.7
  - linux
  except:
  - tags
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    CODECOV_TOKEN: "a0ed9aa4-e4d9-4b24-bf50-0d54e407bd92"

Python 3:
  script:
  - "PY_EXE=python3 bash ./run-tests-for-ci.sh"
  tags:
  - python3
  - linux
  except:
  - tags
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  variables:
    CODECOV_TOKEN: "a0ed9aa4-e4d9-4b24-bf50-0d54e407bd92"

Python 3 CLI Tool:
  script:
  - "PY_EXE=python3 bash ./test-command-line-tool.sh python3"
  tags:
  - python3
  - linux
  except:
  - tags

Documentation:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - export RELATE_LOCAL_TEST_SETTINGS=`pwd`/local_settings_example.py
  - ". ./build-docs.sh"
  tags:
  - python3
  only:
  - master

Mypy:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-mypy.sh
  - ". ./prepare-and-run-mypy.sh python3 mypy==0.641"
  tags:
  - python3
  except:
  - tags

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh relate course accounts tests bin image_upload formats questionnaire survey"
  tags:
  - python3
  except:
  - tags
