language: python
cache: pip
install: true
branches:
  only:
    - custom_docker_image

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - cd docker-image-run-py
  - bash ./docker-build.sh
  - docker build -t $DOCKER_REPO:$COMMIT .
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:latest
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - rm code_feedback.py code_runpy_backend.py

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO
