language: python
cache: pip
install: true
script:
  - deactivate && echo "Deactivated exist virtualenv."
  - bash ./run-travis-ci.sh
env:
  - PY=true PY_EXE=python2.7
  - PY=true PY_EXE=python3.5
  - Flake8=true PY_EXE=python3.5
  - Mypy=true PY_EXE=python3.6
