dist: trusty
sudo: required
service:
  - docker
language: python
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  pip: true
  directories:
    - $HOME/docker
install: true
matrix:
  include:
  - python: "2.7"
    env: RL_TRAVIS_TEST=test PY_EXE=python2.7
  - python: "3.5"
    env: RL_TRAVIS_TEST=test PY_EXE=python3.5
  - python: "3.6"
    env: RL_TRAVIS_TEST=cmdline PY_EXE=python3.6
  - python: "3.5"
    env: RL_TRAVIS_TEST=flake8 PY_EXE=python3.5
  - python: "3.6"
    env: RL_TRAVIS_TEST=mypy PY_EXE=python3.6
script:
  - bash ./run-travis-ci.sh
