sudo: required
service:
  - docker
language: python
cache: pip
install: true
before_script:
  - curl -L -O -k https://gist.githubusercontent.com/dzhuang/7eba18f8a38107c0f7bba8621448f298/raw/cc46d1d003e4975d344140ccfb4e9a07a3e7001d/create-docker-tls.sh
  - sudo chmod 777 ./create-docker-tls.sh
  - bash ./create-docker-tls.sh RELATE_LOCAL
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker pull inducer/relate-runpy-i386
  - docker ps
script:
  - bash ./run-travis-ci.sh
env:
  - PY=true PY_EXE=python2.7
  - PY=true PY_EXE=python3.5
  - Flake8=true PY_EXE=python3.5
  - Mypy=true PY_EXE=python3.5
