# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0088_rename_shown_in_participant_grade_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationpreapproval',
            name='provided_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Provided name'),
        ),
    ]
