# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0089_gradingopportunity_hide_superseded_grade_history_before'),
        ('course', '0089_participationpreapproval_provided_name'),
    ]

    operations = [
    ]
