# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0090_add_visitor_and_impersonator_fields_to_fpv'),
        ('course', '0089_participationpreapproval_provided_name'),
    ]

    operations = [
    ]
