# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0092_unicode_literals'),
        ('course', '0089_participationpreapproval_provided_name'),
    ]

    operations = [
    ]
