# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0097_add_permissions_related_name'),
        ('course', '0089_participationpreapproval_provided_name'),
    ]

    operations = [
    ]
