# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0101_add_ticket_facility_and_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowaccessexceptionentry',
            name='permission',
            field=models.CharField(choices=[('view', 'View the flow'), ('submit_answer', 'Submit answers'), ('end_session', 'End session'), ('change_answer', 'Change already-graded answer'), ('see_correctness', 'See whether an answer is correct'), ('see_answer_before_submission', 'See the correct answer before answering'), ('see_answer_after_submission', 'See the correct answer after answering'), ('cannot_see_flow_result', 'Cannot see flow result'), ('set_roll_over_expiration_mode', "Set the session to 'roll over' expiration mode"), ('see_session_time', 'See session time'), ('lock_down_as_exam_session', 'Lock down as exam session'), ('send_email_about_flow_page', 'Send emails about the flow page to course staff'), ('send_submit_notif_email', 'Send flow submission notification email to coursestaff'), ('cannot_see_in_participant_grade_book', 'Cannot see in participant grade book'), ('cannot_see_result_in_participant_grade_book', 'Cannot see result in participant grade book')], max_length=50, verbose_name='Permission'),
        ),
    ]
