# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0101_add_ticket_facility_and_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpagevisit',
            name='page_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='course.FlowPageData', verbose_name='Page data'),
        ),
    ]
