# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import json

def add_stringfied_pagedata(apps, schema_editor):
    FlowPageData = apps.get_model("course", "FlowPageData")

    for fpd in FlowPageData.objects.all():
        if fpd.data:
            fpd.data_stringfied = json.dumps(fpd.data, sort_keys=True)[:1000]
            fpd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0104_add_skip_during_manual_grading_permission_to_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpagedata',
            name='data_stringfied',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='Stringfied data'),
        ),
        migrations.RunPython(add_stringfied_pagedata)
    ]
