# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0106_add_auth_tokens_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shown_in_calendar',
            field=models.BooleanField(default=True,
                                      help_text="Shown in students' calendar",
                                      verbose_name='Shown in calendar'),
        ),
        migrations.RenameField(
            model_name='flowpagedata',
            old_name='ordinal',
            new_name='page_ordinal',
        ),
    ]
