# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0112_add_effective_time_to_gradechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsession',
            name='credit_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True, verbose_name='Credit percentage'),
        ),
        migrations.AddField(
            model_name='gradechange',
            name='credit_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True, verbose_name='Credit percentage'),
        ),
    ]
