# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 04:38
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_credit_percentages(apps, schema_editor):
    GradeChange = apps.get_model("course", "GradeChange")  # noqa
    target_grade_changes = (
        GradeChange.objects.all())

    FlowSession = apps.get_model("course", "FlowSession")  # noqa
    target_flow_sessions = FlowSession.objects.filter(
        in_progress=False,
        max_points__isnull=False,
        points__isnull=False
    )
    for fs in target_flow_sessions:
        fs.credit_percentage = 100
        fs.save()

    for gc in target_grade_changes:
        gc.credit_percentage = 100
        gc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0112_add_effective_time_to_gradechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsession',
            name='credit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Credit percentage'),
        ),
        migrations.AddField(
            model_name='gradechange',
            name='credit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Credit percentage'),
        ),
        migrations.RunPython(set_default_credit_percentages),
    ]
