# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_upload.storages
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('image_upload', '0001_initial'), ('image_upload', '0002_sessionpage_image'), ('image_upload', '0003_image_file_last_modified'), ('image_upload', '0004_split_image_model_into_two_models'), ('image_upload', '0005_flowpageimage_order'), ('image_upload', '0006_alter_flowsessionimage_model'), ('image_upload', '0007_add_image_data_field'), ('image_upload', '0008_add_use_image_data_field'), ('image_upload', '0009_allow_image_text_null'), ('image_upload', '0010_add_verbosed_name_for_time_field'), ('image_upload', '0011_change_on_delete_behavior'), ('image_upload', '0012_alter_fields_on_flowpageimage'), ('image_upload', '0013_remove_UserImage_model_modify_storage')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_inst_id_unique_and_updates'),
        ('course', '0086_flowpagedata_bookmarked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=image_upload.storages.UserImageStorage(), upload_to=image_upload.storages.user_flowsession_img_path)),
                ('slug', models.SlugField(blank=True, max_length=256)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_page_id', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='Course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('flow_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_image_data', to='course.FlowSession', verbose_name='Flow session')),
                ('order', models.SmallIntegerField(default=0)),
                ('image_text', models.TextField(blank=True, help_text='The html for the FlowPageImage', null=True, verbose_name='Related Html')),
                ('is_image_textify', models.BooleanField(default=False, verbose_name='Load textified Image?')),
                ('image_data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='External image data')),
                ('use_image_data', models.BooleanField(default=False, verbose_name='Use external Image data?')),
            ],
            options={
                'ordering': ('id', 'creation_time'),
            },
        ),
    ]
