# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_upload.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0086_flowpagedata_bookmarked'),
        ('accounts', '0008_inst_id_unique_and_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, storage=image_upload.models.UserImageStorage(), upload_to=image_upload.models.user_flowsession_img_path)),
                ('slug', models.SlugField(blank=True, max_length=256)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_page_id', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='Course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('flow_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_image_data', to='course.FlowSession', verbose_name='Flow session')),
                ('image_text', models.TextField(blank=True, help_text='The html for the FlowPageImage', null=True, verbose_name='Related Html')),
                ('is_image_textify', models.BooleanField(default=False, verbose_name='Load textified Image?')),
                ('image_data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='External image data')),
                ('use_image_data', models.BooleanField(default=False, verbose_name='Use external Image data?')),
                ('is_temp_image', models.BooleanField(default=False, verbose_name='Is the image for temporary use?')),
            ],
            options={
                'ordering': ('id', 'creation_time'),
            },
        ),
    ]
