# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import image_upload.storages


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_rename_FlowPageImage_file_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpageimage',
            name='image',
            field=models.ImageField(max_length=500, storage=image_upload.storages.UserImageStorage(), upload_to=image_upload.storages.user_flowsession_img_path),
        ),
    ]
