# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_upload.models
import image_upload.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0086_flowpagedata_bookmarked'),
        ('image_upload', '0003_image_file_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=image_upload.storages.UserImageStorage(), upload_to=image_upload.models.user_flowsession_img_path)),
                ('slug', models.SlugField(blank=True, max_length=256)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_page_id', models.CharField(max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('flow_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_image_data', to='course.FlowSession', verbose_name='Flow session')),
            ],
            options={
                'ordering': ('id', 'creation_time'),
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=image_upload.storages.UserImageStorage(), upload_to=image_upload.storages.user_directory_path)),
                ('slug', models.SlugField(blank=True, max_length=256)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'ordering': ('id', 'creation_time'),
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sessionpageimage',
            name='flow_session',
        ),
        migrations.RemoveField(
            model_name='sessionpageimage',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='SessionPageImage',
        ),
    ]
