# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_split_image_model_into_two_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpageimage',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
