# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0005_flowpageimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowpageimage',
            name='image_text',
            field=models.TextField(default=b'', help_text='The html for the FlowPageImage', verbose_name='Related Html'),
        ),
        migrations.AddField(
            model_name='flowpageimage',
            name='is_image_texify',
            field=models.BooleanField(default=False, verbose_name=b'Image textified?'),
        ),
    ]
