# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0007_auto_20160508_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowpageimage',
            name='is_image_texify',
        ),
    ]
