# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0008_add_use_image_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpageimage',
            name='image_text',
            field=models.TextField(blank=True, help_text='The html for the FlowPageImage', null=True, verbose_name='Related Html'),
        ),
    ]
