# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0009_allow_image_text_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Time'),
        ),
    ]
