# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0010_add_verbosed_name_for_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpageimage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='flowpageimage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='flowpageimage',
            name='flow_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_image_data', to='course.FlowSession', verbose_name='Flow session'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
