# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0011_change_on_delete_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpageimage',
            name='is_image_textify',
            field=models.BooleanField(default=False, verbose_name='Load textified Image?'),
        ),
        migrations.AlterField(
            model_name='flowpageimage',
            name='use_image_data',
            field=models.BooleanField(default=False, verbose_name='Use external Image data?'),
        ),
    ]
