# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import image_upload.storages


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0012_alter_fields_on_flowpageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='creator',
        ),
        migrations.AlterField(
            model_name='flowpageimage',
            name='file',
            field=models.ImageField(storage=image_upload.storages.UserImageStorage(), upload_to=image_upload.storages.user_flowsession_img_path),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
