# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('course', '0102_learningwhat_specific_migrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPerParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('filled', 'Filled'), ('unfilled', 'Unfilled')], max_length=50, verbose_name='State')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Participation', verbose_name='Participation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question', verbose_name='Statistics Question')),
            ],
            options={
                'ordering': ('question__fieldname', 'participation__user__institutional_id'),
                'verbose_name': 'Survey Question Status',
                'verbose_name_plural': 'Survey Question Status',
            },
        ),
    ]
