# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('course', '0102_learningwhat_specific_migrate'),
        ('course_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsSurvey',
            fields=[
                ('questionnaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.Questionnaire')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Course Statistics Surveys',
                'verbose_name': 'Course Statistics Survey',
                'ordering': ('course', 'title'),
            },
            bases=('questionnaire.questionnaire',),
        ),
        migrations.AlterUniqueTogether(
            name='statisticssurvey',
            unique_together=set([('course',)]),
        ),
    ]
