# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0101_add_ticket_facility_and_validity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Survey Title')),
                ('creation_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creation time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='Course')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='questionnaire.Questionnaire', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'Course Statistics Survey',
                'verbose_name_plural': 'Course Statistics Surveys',
                'ordering': ('course', 'questionnaire__title'),
            },
        ),
        migrations.CreateModel(
            name='ParticipationSurveyQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', jsonfield.fields.JSONField(blank=True, help_text='The text answer related to the question', verbose_name='Answer')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creation time')),
                ('state', models.CharField(choices=[('filled', 'Filled'), ('unfilled', 'Unfilled')], default='unfilled', max_length=50, verbose_name='State')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Participation', verbose_name='Participation')),
                ('question', models.ForeignKey(help_text='The question that this is an answer to', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
                ('survey', models.ForeignKey(help_text='The survey', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.CourseSurvey')),
                ('user', models.ForeignKey(help_text='The user who lastly supplied this answer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participationsurveyquestionanswer',
            unique_together=set([('survey', 'participation', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursesurvey',
            unique_together=set([('course',)]),
        ),
    ]
